version: '3.8'
services:
  stat-server:
    build: stat
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  main-service:
    build: main
    image: main-server
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
      - STATS_SERVER_URL=http://stat-server:9090

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
