version: '3.1'
services:
  stat-server:
    build: stat
    image: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - SPRING.DATASOURCE.USERNAME=stat
      - SPRING.DATASOURCE.PASSWORD=stat

  stat-db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  main-service:
    build: main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/main-db
      - SPRING.DATASOURCE.USERNAME=main
      - SPRING.DATASOURCE.PASSWORD=main

  main-db:
    image: postgres:13.7-alpine
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main